In [2]:
import tensorflow as tf
import datetime
import keras

import numpy as np
import pandas as pd

#For data saving
import pickle
import random
#other imports
import os
import keras.backend as K

In [3]:
#From Lab-of-origins
def convert_onehot2D(list_of_seqs):
    list_of_onehot2D_seqs = np.zeros((len(list_of_seqs),4,len(list_of_seqs[0])))
    nt_dict = {'A':[1,0,0,0],'T':[0,1,0,0],'G':[0,0,1,0],'C':[0,0,0,1], 'N':[0,0,0,0]}
    count = 0
    for seq in list_of_seqs:
        if len(seq) > 1:
            for letter in range(len(seq)):
                for i in range(4):
                    list_of_onehot2D_seqs[count][i][letter] = (nt_dict[seq[letter]])[i]
        count += 1
    return list_of_onehot2D_seqs

In [4]:
# From Lab-of-origins
def pad_dna(seqs,maxlen):
    start = time.time()
    padded_seqs = [''] * len(seqs)
    for i in seqs:
        if len(i) > maxlen:
            i = i[:maxlen]
            maxlen = len(i)
    for j in range(len(seqs)):
        if len(seqs[j]) > maxlen:
            seq = seqs[j][0:maxlen]
        else:
            seq = seqs[j]
        padded_seqs[j] = seq + "N" * (maxlen - len(seq))
    end = time.time()
    return padded_seqs

In [5]:
# From Lab-of-origins
def convert_seq_to_atgcn(seq):
    char_list = list(string.printable)
    for i in ['A','T','G','C','a','t','g','c']:
        char_list.remove(i)
    for ch in char_list:
        if ch in seq:
            seq=seq.replace(ch,"N")
    return seq.upper()

In [6]:
def append_rc(seqs,filter_length):
    start = time.time()
    full_seqs = [''] * len(seqs)
    rc_dict = {'A':'T','T':'A','G':'C','C':'G','N':'N'}
    for j in range(len(seqs)):
        fwd_seq = seqs[j]
        complement_seq = ''
        for n in fwd_seq:
            complement_seq += rc_dict[n]
        full_seqs[j] = fwd_seq + 'N'*filter_length + complement_seq[::-1] #[::-1] reverses string 
    end = time.time()
    return full_seqs

In [14]:
with open('../partition_train_val_a.dat', 'rb') as f:
    partition = pickle.load(f)
train_samples = partition['train']
val_samples = partition['validation']
random.shuffle(train_samples)
random.shuffle(val_samples)
labels = partition['labels']
partition['train'] = train_samples
partition['validation'] = val_samples
'''
print(len(train_samples))
for ID in train_samples:
    if labels[ID][0][0] == 0:
        train_samples.remove(ID)
print(len(train_samples))
print(labels[train_samples[0]])

print(len(val_samples))
for ID in val_samples:
    if labels[ID][0][0] == 0:
        val_samples.remove(ID)
print(len(val_samples))
print(labels[val_samples[0]])
'''

'\nprint(len(train_samples))\nfor ID in train_samples:\n    if labels[ID][0][0] == 0:\n        train_samples.remove(ID)\nprint(len(train_samples))\nprint(labels[train_samples[0]])\n\nprint(len(val_samples))\nfor ID in val_samples:\n    if labels[ID][0][0] == 0:\n        val_samples.remove(ID)\nprint(len(val_samples))\nprint(labels[val_samples[0]])\n'

In [ ]:
train_samples, val_samples = remove_zero_category()

In [12]:
Y_train = np.zeros((200, 2), dtype=np.int8)
X_train = np.zeros((200, 1000, 4), dtype=np.int8)

In [7]:
with open('../partition_test_a.dat', 'rb') as f:
    partition = pickle.load(f)
test_samples_IDs = partition['test']

with open('../test_labels.dat', 'rb') as f:
    test_labels = pickle.load(f)
print(len(test_labels))

16382


In [17]:
count_input_train = 0
a = train_samples[count_input_train]
X_train[0, :, :] = np.load('../model_11_data_4/' + train_samples[count_input_train] + '.npy') 
Y_train[0, :] = labels[a] 
print(Y_train[0][0])

1


In [ ]:
count_input_train = 0
count_input_validation = 0
while count_input_train < len(train_samples):
    Y_train = np.zeros((200, 2), dtype=np.int8)
    X_train = np.zeros((200, 1000, 4), dtype=np.int8)
    Y_val = np.zeros((40, 2), dtype=np.int8)
    X_val = np.zeros((40, 1000, 4), dtype=np.int8)
    if count_input_train < (len(train_samples) - 200):
        for i in range(0, 200):
            a = train_samples[count_input_train]
            X_train[i, :, :] = np.load('../model_11_data_4/' + train_samples[count_input_train] + '.npy') 
            Y_train[i, :] = labels[a] 
            count_input_train += 1
            if count_input_train < 2:
                for j in range(1, 2):
                    print(X_train[j][300:400])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]

In [11]:
expected = []
count_1 = 0
count_0 = 0

for label in test_labels[0:16200]:
    expected.append(label[0][0])
    if label[0][0] == 1:
        count_1 += 1
    elif label[0][0] == 0:
        count_0 += 1
    else:
        print(label[0][0])
        
print(expected[0])
print(count_1)
print(count_0)

1
7632
8568
